name: Daily Newsletter

concurrency:
  group: daily-newsletter
  cancel-in-progress: true

on:
  schedule:
    - cron: "30 3 * * *" # Time scheduled to run
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Requirements has cached... please un-cache :)
      # Hopefully pip can just magically fix it
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download SpaCy model
        run: python -m spacy download en_core_web_sm

      - name: Run newsletter generator
        env:
          Tavily_DEV: ${{ secrets.TAVILY_DEV }}
          Google_AI_Key: ${{ secrets.GOOGLE_AI_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          OPENROUTER: ${{ secrets.OPENROUTER }}
          NVIDIA_DEV: ${{ secrets.NVIDIA_DEV }}
        run: python newsletter_generator.py
